### ISSUE TITLE
Total commits number

### ISSUE THREAD

**Issue by yousefelassal** [LuciNyan/pixel-profile#5]
# Bug report

## Description / Observed Behavior

The shown total commits number is not for the current year as displayed in the card.
![github-stats](https://github.com/LuciNyan/pixel-profile/assets/76617202/5bd07224-1e2e-43c8-a712-b68787fcad10)

## Expected Behavior

The expected number for my profile is 1.3k.
![total-commits](https://github.com/LuciNyan/pixel-profile/assets/76617202/80123f72-2739-4296-a56e-e50d910d5a42)

## Additional Context

I skimmed through the code, I've noticed you're using the GraphQL API.
I don't know if that would help but the api provides a `from` variable which could be passed to the `contributionCollection`
```gql
contributionsCollection(from: "2024-01-01T00:00:00Z") {
  totalCommitContributions
  startedAt
}
```
when passing the start of the year it would return the expected number of contributions
```json
"contributionsCollection": { 
   "totalCommitContributions": 1337,
   "startedAt": "2024-01-01T00:00:00Z"
},
```

**Comment by LuciNyan** [comment]
Thank you for taking the time to provide such thorough feedback! <3

**Comment by LuciNyan** [comment]
Hi @yousefelassal 👋🏻 ! Could you take a look at this https://github.com/LuciNyan/pixel-profile/pull/7 THX!

**Comment by yousefelassal** [comment]
the numbers make much more sense now! 
Thank you for open sourcing such great project I love it!!

**Comment by LuciNyan** [comment]
You're so kind! thank you! I'm pleased it's been useful to others. hh
