### ISSUE TITLE
Abnormal avatar generation

### ISSUE THREAD

**Issue by Gloridust** [LuciNyan/pixel-profile#6]
My Link：https://pixel-profile.vercel.app/api/github-stats?username=Gloridust
The effect of avatar synthesis is not very good, hope to fix it🤓
![74081708930406_ pic](https://github.com/LuciNyan/pixel-profile/assets/88082356/229eeb20-b8a0-4b87-9349-0169fcb2b995)

**Comment by LuciNyan** [comment]
Thanks for the feedback!

**Comment by LuciNyan** [comment]
Hi @Gloridust 👋 The bug has been fixed. 🚀 Please feel free to reach out if any other issues come up. xD

**Comment by Gloridust** [comment]
Very well!! Thx
